PAE-831-New param in Course endpoints that allows the sorting/ordering of the course_runs by start date
Pearson-Advance/course-discovery pull request #1
Opened 2021-09-10 19:27 UTC by elvinquero

When someone does a request to the `api/v1/courses/{key}` endpoint in discovery. The course runs array in the resulting request is not implicitly ordered. Now there is a new param called `course_runs_sort_by` that when added, allows for the sorting ordering of those records. The param uses the same behavior as the ordering parameter in DRF. One can do `api/v1/courses/{key}/?course_runs_sort_by=-start` is one wants to order them in DESC or `api/v1/courses/edX%2BDemoX/?course_runs_sort_by=start` to order them in ASC.

Right now the only possible accepted fields are key and start, more fields could be added easily. 

[PAE-831](https://pearsonadvance.atlassian.net/browse/PAE-831) for reference.

2021-09-14 14:35 UTC, Squirrel18 requested changes

2021-09-14 14:35 UTC, Squirrel18 commented on course_discovery/apps/api/filters.py
> +class CourseRunOrderingFilter(OrderingFilter):
Missing doc-string. @elvinquero

2021-09-14 14:35 UTC, Squirrel18 commented on course_discovery/apps/api/filters.py
> +    def get_ordering(self, request, queryset, view):
Missing doc-string. @elvinquero

2021-09-14 14:35 UTC, Squirrel18 commented on course_discovery/apps/api/filters.py
> +    def filter_queryset(self, request, queryset, view):
Missing doc-string. @elvinquero

2021-09-14 14:35 UTC, Squirrel18 commented on course_discovery/apps/api/filters.py
> +        params = request.query_params.get(self.ordering_param)
Add a blank line after this line to separate the assignment and logic blocks. @elvinquero

2021-09-14 14:35 UTC, Squirrel18 commented on course_discovery/apps/api/filters.py
> +        if params:
```suggestion
        if not params:
```
This avoids nested code. @elvinquero

2021-09-14 14:35 UTC, Squirrel18 commented on course_discovery/apps/api/filters.py
> +            ordering = [f for f in fields if f.lstrip('-') in self.allowed_custom_filters]
```suggestion
            ordering = [filter for filter in fields if filter.lstrip('-') in self.allowed_custom_filters]
```

2021-09-14 14:35 UTC, Squirrel18 commented on course_discovery/apps/api/filters.py
> +        return self.get_default_ordering(view)
This block can be an inline return statement. @elvinquero

2021-09-14 14:35 UTC, Squirrel18 commented on course_discovery/apps/api/filters.py
> +        ordering = self.get_ordering(request, queryset, view)
Add a blank line after this line. @elvinquero

2021-09-14 14:35 UTC, Squirrel18 commented on course_discovery/apps/api/v1/views/courses.py
> +            # Apply an order to the course_runs by the parameter "course_runs_sort_by"
A period is missing at the end of the comment. @elvinquero

2021-09-14 16:24 UTC, elvinquero commented
I made the default ordering as `-start`. This will then has to change when the PR is opened on the Open edX site.

2021-09-14 22:14 UTC, Squirrel18 commented on course_discovery/apps/api/filters.py
> +
Unnecessary blank line. @elvinquero

2021-09-14 22:14 UTC, Squirrel18 commented on course_discovery/apps/api/filters.py
> +
Unnecessary blank line. @elvinquero

2021-09-14 22:14 UTC, Squirrel18 commented on course_discovery/apps/api/filters.py
> +
Unnecessary blank line. @elvinquero

2021-09-14 22:14 UTC, Squirrel18 commented on course_discovery/apps/api/filters.py
> +            view: The CourseRunViewset
A period at the end of the line. @elvinquero

2021-09-14 22:14 UTC, Squirrel18 commented on course_discovery/apps/api/filters.py
> +            view: The CourseRunViewset
A period at the end of the line. @elvinquero

2021-09-15 01:18 UTC, diegomillan approved these changes
Good job @elvinquero ! LGTM

2021-09-15 02:42 UTC, Squirrel18 approved these changes

2021-09-15 11:52 UTC, merged