PADV-377 - Update inputs in build and push workflows
Pearson-Advance/course-discovery pull request #6
Opened 2023-04-14 19:33 UTC by sergivalero20

## Ticket

https://agile-jira.pearson.com/browse/PADV-377

## Description

This PR changes some inputs as [tutor-build-image-action](https://github.com/Pearson-Advance/tutor-build-image-action/tree/vue/PADV-377) updated the names of its parameters.

## Type of Change

- [x] Change and add new input in workflow for prod.
- [x] Change and add new input in workflow for stage.

## How to test

- Create a test PR in the discovery repository.
- Merge this PR into the target branch.
- Check that the Github Action is triggered by the PR merge event.
- Check the output of the image build creation for any issues or silent issues.
-  When the process is complete, check the Docker Hub Pearson repository and verify that the image has been built (https://hub.docker.com/repository/docker/paops/discovery-tutor/general).
-  Use the image in a local environment to test it out.
- You can use this repo https://github.com/Pearson-Advance/discovery/tree/vue/PADV-356.tests to perform any tests

## Reviewers

- [x] @Squirrel18
- [x] @anfbermudezme

2023-04-14 19:46 UTC, anfbermudezme approved these changes
LGTM

2023-04-17 13:52 UTC, Squirrel18 requested changes

2023-04-17 13:52 UTC, Squirrel18 commented on .github/workflows/ build-push-image-main.yml
> +          tutor-pearson-plugin: ${{ vars.TUTOR_PEARSON_PLUGIN_MAIN }}
It's not necessary to get this from environment values. @sergivalero20

2023-04-17 18:25 UTC, Squirrel18 approved these changes

2023-04-17 19:11 UTC, merged