PADV-487 - Migrate Course Discovery to olive version.
Pearson-Advance/course-discovery pull request #8
Opened 2023-05-04 17:09 UTC by anfbermudezme

WIP.

2023-05-09 22:37 UTC, Squirrel18 requested changes

2023-05-09 22:37 UTC, Squirrel18 commented on course_discovery/apps/api/v1/views/courses.py
> +            course_runs = filters.CourseRunOrderingFilter().filter_queryset(self.request, course_runs, CourseRunViewSet)
Line too long? @anfbermudezme

2023-05-09 22:37 UTC, Squirrel18 commented on docs/custom_features.md
> +array in the resulting request is not implicitly ordered.
```suggestion
ordered by course start date. Making the respective discovery it was determined that the array of course runs in the resulting request is not implicitly ordered.
```

2023-05-10 02:28 UTC, alexjmpb approved these changes

2023-05-12 02:58 UTC, Squirrel18 approved these changes

2023-05-12 15:47 UTC, merged